version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-3"
    REACT_APP_API_SERVICE_URL: "http://localhost:5004"

phases:
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region eu-west-3 \
          | docker login --username AWS --password-stdin 895672350208.dkr.ecr.eu-west-3.amazonaws.com
  build:
    commands:
      - echo building images...
      - >
        docker build \
          -f services/users/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/test-driven-users:prod \
          ./services/users
      - >
        docker build \
          -f services/client/Dockerfile.prod \
          -t 895672350208.dkr.ecr.eu-west-3.amazonaws.com/test-driven-client:prod \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL \
          ./services/client
  post_build:
    commands:
    - docker push 895672350208.dkr.ecr.$eu-west-3.amazonaws.com/test-driven-users:prod
    - docker push 895672350208.dkr.ecr.$eu-west-3.amazonaws.com/test-driven-client:prod
